char * call_getcwd();
char ** parse( char * in, char * del);
void execute (char * str);
void feed(char * in);
void sigintHandler(int sig_num);
void printSajictorPrompt ();
int has_pipe (char * line);
void exepipe(char * line);
int has_redir(char * line);
int * redir_order(char * line);
void symexe(char * line);
